# Generated by Django 4.2.13 on 2024-06-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readytoplay',
            name='user_name',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists'}, max_length=100, unique=True),
        ),
    ]
