# Generated by Django 4.2.13 on 2024-06-25 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_readytoplay_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readytoplay',
            old_name='user_name',
            new_name='username',
        ),
    ]
