# Generated by Django 4.2.11 on 2024-05-15 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email_alter_user_username_tokens_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokens',
            name='expired_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 15, 12, 53, 47, 102350, tzinfo=datetime.timezone.utc)),
        ),
    ]
