# Generated by Django 4.2.11 on 2024-05-15 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_tokens_expired_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokens',
            name='expired_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 15, 12, 54, 45, 288177, tzinfo=datetime.timezone.utc)),
        ),
    ]
