# Generated by Django 4.2.11 on 2024-05-15 11:57

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_tokens_expired_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokens',
            name='expired_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 15, 12, 57, 6, 422413, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, error_messages={'unique': 'A user with that email already exists'}, max_length=255, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, error_messages={'unique': 'A user with that username already exists'}, max_length=50, unique=True),
        ),
    ]
