# Generated by Django 4.2.13 on 2024-06-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='retype_password',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
