# Generated by Django 4.2.11 on 2024-05-19 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_avatar_link_alter_tokens_expired_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='method',
            field=models.CharField(default='email', max_length=25),
        ),
        migrations.AlterField(
            model_name='tokens',
            name='expired_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 19, 16, 0, 15, 137394, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar_link',
            field=models.ImageField(default='avatars/default.png', upload_to='avatars'),
        ),
    ]
