# Generated by Django 4.2.11 on 2024-06-02 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_auth_method_alter_tokens_expired_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_matches',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='auth',
            name='content',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tokens',
            name='expired_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 2, 10, 40, 51, 992834, tzinfo=datetime.timezone.utc)),
        ),
    ]
