# Generated by Django 4.2.11 on 2024-06-02 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_total_matches_alter_auth_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_no', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=30)),
                ('image', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='tokens',
            name='expired_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 2, 11, 21, 57, 237234, tzinfo=datetime.timezone.utc)),
        ),
    ]
