# Generated by Django 4.2.11 on 2024-06-02 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_level_alter_tokens_expired_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokens',
            name='expired_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 2, 11, 31, 54, 706402, tzinfo=datetime.timezone.utc)),
        ),
    ]
