# Generated by Django 4.2.11 on 2024-06-03 13:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_tokens_expired_date_invitation_blocked_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokens',
            name='expired_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 3, 14, 53, 5, 466434, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('cuuid', models.UUIDField(primary_key=True, serialize=False)),
                ('last_message', models.TextField(max_length=500)),
                ('status', models.TextField()),
                ('last_date', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
