# Generated by Django 4.2.11 on 2024-06-03 13:59

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_tokens_expired_date_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokens',
            name='expired_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 3, 14, 59, 14, 14776, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('time', models.DateTimeField(default=datetime.datetime(2024, 6, 3, 13, 59, 14, 17198, tzinfo=datetime.timezone.utc))),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_draw', models.BooleanField(default=False)),
                ('player1_goals', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('player2_goals', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('match_id', models.UUIDField(primary_key=True, serialize=False)),
                ('player1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player1_match', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player2_match', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner_match', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
