# Generated by Django 4.2.11 on 2024-06-03 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_tokens_expired_date_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='time',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='tokens',
            name='expired_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 3, 15, 1, 11, 564293, tzinfo=datetime.timezone.utc)),
        ),
    ]
