# Generated by Django 4.2.11 on 2024-06-03 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_match_time_alter_tokens_expired_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name_plural': 'Matches'},
        ),
        migrations.AlterField(
            model_name='tokens',
            name='expired_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 3, 15, 6, 38, 222213, tzinfo=datetime.timezone.utc)),
        ),
    ]
