# Generated by Django 4.2.11 on 2024-06-28 09:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_match_options_alter_tokens_expired_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='conversation_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation_id_friend', to='users.conversation'),
        ),
        migrations.AlterField(
            model_name='tokens',
            name='expired_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 28, 10, 11, 32, 883683, tzinfo=datetime.timezone.utc)),
        ),
    ]
